import { Amplify } from 'aws-amplify';

// This will be populated during build/deployment
// For local development, you can use amplify_outputs.json
// For production, Amplify will inject the outputs automatically

let amplifyConfig: any = {};

// Try to load from amplify_outputs.json (generated by sandbox or deployment)
if (typeof window !== 'undefined') {
  // Client-side: try to load from public folder
  try {
    // In production, Amplify will inject this automatically
    // For local dev, you can manually create amplify_outputs.json
  } catch (e) {
    console.warn('Could not load amplify_outputs.json');
  }
}

// Configure Amplify
// The outputs will be injected by Amplify during deployment
// For now, we'll set up a basic config that will be overridden
if (typeof window !== 'undefined') {
  Amplify.configure(amplifyConfig, { ssr: true });
}

export { Amplify };

